// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, http;

  http = require('http');

  express = require('express');

  app = express();

  app.use('/', express["static"](__dirname));

  http.createServer(app).listen(3000);

}).call(this);
